/**
 * Copies the compiled ABIs of the two production contracts into the frontend as
 * a TypeScript module.
 *
 * Why generate rather than hand-write: an ABI typed by hand drifts the moment a
 * parameter is added, and the failure mode is a transaction that encodes to
 * something the contract does not implement — a revert with no name, at the
 * user's expense. Generating it makes `npm run build` the only thing that can
 * change it.
 *
 * Why the generated file is committed even though `artifacts/` is not: the
 * frontend must build on a machine that has never compiled the contracts (a
 * Vercel build, a fresh clone). Committing the output keeps the frontend a
 * standalone package; `npm run export-abi` regenerates it, and CI fails if the
 * committed copy has drifted.
 *
 * `as const` is load-bearing. Without it every ABI entry widens to `string` and
 * wagmi's inference produces `unknown` argument types, which silently removes
 * the compile-time check that a call passes the right arguments.
 *
 * Usage: npm run export-abi [-- --check]
 *   --check exits non-zero if the file on disk differs from what would be
 *   written, without writing anything. That is the CI form.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

/** Contracts whose ABI the frontend needs. Mocks and interfaces stay out. */
const CONTRACTS = ["CallRegistry", "PriceOracleResolver"];

const OUT = join(root, "frontend", "src", "contracts", "abis.ts");

function abiOf(name) {
  const path = join(root, "artifacts", "contracts", `${name}.sol`, `${name}.json`);
  if (!existsSync(path)) {
    throw new Error(`No artifact for ${name} at ${path}. Run \`npm run build\` first.`);
  }
  return JSON.parse(readFileSync(path, "utf8")).abi;
}

const banner = `// Generated by scripts/export-abi.js — do not edit.
// Regenerate with \`npm run build && npm run export-abi\` from the repository root.
`;

const body = CONTRACTS.map((name) => {
  const constName = `${name.charAt(0).toLowerCase()}${name.slice(1)}Abi`;
  return `export const ${constName} = ${JSON.stringify(abiOf(name), null, 2)} as const;\n`;
}).join("\n");

const contents = `${banner}\n${body}`;

if (process.argv.includes("--check")) {
  const current = existsSync(OUT) ? readFileSync(OUT, "utf8") : "";
  if (current !== contents) {
    console.error(
      `${OUT} is out of date with the compiled artifacts.\n` +
        "Run `npm run build && npm run export-abi` and commit the result.",
    );
    process.exit(1);
  }
  console.log("ABIs are up to date.");
} else {
  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, contents);
  console.log(`Wrote ${CONTRACTS.length} ABIs to ${OUT}`);
}
